services:
  cua-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: cua-image
    container_name: cua-image
    ports:
      - "5900:5900"
    environment:
      - DISPLAY=:99
    command: >
      /bin/sh -c "
      Xvfb :99 -screen 0 1280x800x24 >/dev/null 2>&1 & 
      x11vnc -display :99 -forever -rfbauth /home/myuser/.vncpass -listen 0.0.0.0 -rfbport 5900 >/dev/null 2>&1 & 
      export DISPLAY=:99 && 
      startxfce4 >/dev/null 2>&1 & 
      sleep 2 && echo 'Container running!' && 
      tail -f /dev/null
      "