name: open-webui
services:
  open_webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ../open-webui:/app/backend/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mcp_network
  mcp_server_container:
    image: eren_container_paperclip_ai
    container_name: eren_container_mcp_server
    user: "197609:197121"
    ports:
      - "16041:16041"
    volumes:
      - src:/code
    networks:
      - mcp_network
    #    command: /bin/sh -c "/opt/conda/bin/python3 /code/mcp_servers/example_server.py"
    command: uvx mcpo --host 0.0.0.0 --port 16041 -- /opt/conda/bin/python3 /code/mcp_servers/example_server.py
networks:
  mcp_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
volumes:
  src:
    driver: local
    driver_opts:
      type: none
      device: ..
      o: bind