name: paperclip_ai
services:
  paperclip_browser_container:
    build:
      context: .
      dockerfile: DockerfileVM
      secrets:
        - vnc_password
    image: paperclip_browser_container
    container_name: paperclip_browser_container
    environment:
      VNC_PASSWORD_FILE: /run/secrets/vnc_password
      DISPLAY: host.docker.internal:0.0
    ports:
      - "5900:5900"
      - "8000:8000"
    volumes:
      - src:/code
    secrets:
      - browser_automation_api_key
    networks:
      - browser_automation_network
    command: >
      /bin/sh -c "
      Xvfb host.docker.internal:0.0 -screen 0 1280x800x24 >/dev/null 2>&1 & 
      x11vnc -display host.docker.internal:0.0 -forever -rfbauth /home/myuser/.vncpass -listen 0.0.0.0 -rfbport 5900 >/dev/null 2>&1 & 
      export DISPLAY=host.docker.internal:0.0 && 
      startxfce4 >/dev/null 2>&1 & 
      sleep 2 && firefox-esr & 
      python -m fastapi dev browser_api/main.py --port 8000 --host 0.0.0.0 &
      sleep 2 && echo 'Container running!' && 
      tail -f /dev/null
      "

  paperclip_ai:
    build:
      context: .
      dockerfile: DockerfilePython
      args:
        USER_ID: 197609
        GROUP_ID: 197121
        USERNAME: eren
    image: eren_container_paperclip_ai
    container_name: eren_container_paperclip_ai
    user: "197609:197121"
    ipc: host
    volumes:
      - src:/code
    secrets:
      - browser_automation_api_key
    networks:
      - browser_automation_network
    command: /bin/sh -c "export DISPLAY=host.docker.internal:0.0 && /opt/conda/bin/python3 /code/main.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
volumes:
  src:
    driver: local
    driver_opts:
      type: none
      device: ..
      o: bind

secrets:
  vnc_password:
    file: ./secrets/vnc_password.txt
  browser_automation_api_key:
    file: ./secrets/browser_automation_api_key.txt
networks:
  browser_automation_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"