name: paperclip_ai
services:
  paperclip_ai:
    build:
      context: .
      dockerfile: DockerfilePython
      args:
        USER_ID: 197609
        GROUP_ID: 197121
        USERNAME: eren
      secrets:
        - vnc_password
    image: eren_container_paperclip_ai
    container_name: eren_container_paperclip_ai
    user: "197609:197121"
    ipc: host
    volumes:
      - src:/code
    secrets:
      - openai_config
      - vnc_password
    networks:
      - browser_automation_network
    command: /bin/sh -c "export DISPLAY=host.docker.internal:0.0 && /opt/conda/bin/python3 /code/main.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
volumes:
  src:
    driver: local
    driver_opts:
      type: none
      device: ..
      o: bind

secrets:
  openai_config:
    file: secrets/openai_config.json
  vnc_password:
    file: ./secrets/vnc_password.txt
networks:
  browser_automation_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"